mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='polls/')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:question_id>/unvote/", views.unvote, name="unvote"),
]

polls/models.py
"""Contains models for the poll application."""

import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    """
    The Question model.

    Contains two fields, which are the question text and the publication date.
    """

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", default=timezone.now)
    end_date = models.DateTimeField(
        "ending date for voting", default=None, null=True, blank=True
    )

    def __str__(self):
        """Retrieve the question's text."""
        return self.question_text

    def was_published_recently(self):
        """Check whether the poll was published recently."""
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def is_published(self):
        """Check whether the poll is published."""
        return self.pub_date <= timezone.now()

    def can_vote(self):
        """Check whether the user can vote on the poll."""
        if self.end_date:
            return self.is_published() and timezone.now() <= self.end_date
        return self.is_published()


class Choice(models.Model):
    """
    The choice Model.

    There can be many choices to one question.
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    @property
    def votes(self):
        """Return the vote of this choice."""
        return self.vote_set.count()

    def __str__(self):
        """Return the choice's text."""
        return self.choice_text


class Vote(models.Model):
    """
    A vote by the user to a choice in the poll.

    There can be many votes to one choice.
    """

    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/views.py
"""Contains the views of the poll application."""

import logging

from django.contrib import messages
from django.contrib.auth import user_logged_in, user_logged_out, user_login_failed
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question, Vote

logger = logging.getLogger("polls")


class IndexView(generic.ListView):
    """The view of the poll's index page."""

    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        questions = Question.objects.filter(pub_date__lte=timezone.now())
        return questions.order_by("-pub_date")


class DetailView(generic.DetailView):
    """Display choices for a poll."""

    model = Question
    template_name = "polls/detail.html"

    def dispatch(self, request, *args, **kwargs):
        """Check whether the question can be voted on.

        If not, then redirects to the index page with error message.
        """
        question = self.get_object()
        if not question.can_vote():
            error_text = "Access Denied."
            messages.error(request, error_text)
            return HttpResponseRedirect(reverse("polls:index"))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Add user's selected choice to the context, if exists."""
        data = super().get_context_data(**kwargs)
        question = self.get_object()
        user = self.request.user
        if user.is_authenticated:
            marked_vote = user.vote_set.filter(choice__question=question)
            if marked_vote:
                data["marked_choice"] = marked_vote.first().choice
        return data


class ResultsView(generic.DetailView):
    """The view of the results page."""

    model = Question
    template_name = "polls/results.html"


@login_required
def vote(request, question_id):
    """If the user is eligible to vote, cast a vote to the active question."""
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        logger.error(f"Failed to get selected choice for question {question_id}")
        messages.error(request, "Please re-select the choice again.")
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))

    this_user = request.user
    try:
        vote = this_user.vote_set.get(choice__question=question, user=this_user)
        vote.choice = selected_choice
        vote.save()
        vote_id = selected_choice.id
        logger.info(
            f"{this_user} changed vote to vote id: {vote_id} \
on question id: {question.id}"
        )
        messages.success(
            request,
            f'Your vote was changed to \
"{selected_choice.choice_text}"',
        )
    except Vote.DoesNotExist:
        vote = Vote.objects.create(user=this_user, choice=selected_choice)
        logger.info(
            f"{this_user} voted vote id: {selected_choice.id} \
on question id: {question.id}"
        )
        messages.success(
            request,
            f'You have voted \
"{selected_choice.choice_text}"',
        )

    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


@login_required
def unvote(request, question_id):
    """Delete the user's vote, if exists."""
    question = get_object_or_404(Question, pk=question_id)
    this_user = request.user

    try:
        vote = this_user.vote_set.get(choice__question=question, user=this_user)
        logger.info(f"{this_user} deleted vote id: {vote.id} \
on question id: {question.id}")
        vote.delete()
        messages.success(request, "You've successfully deleted your vote")
    except Vote.DoesNotExist:
        messages.error(request, "ERROR: You haven't vote yet")
        logger.error(
            f"{this_user} tried to delete non-existent\
vote on question id: {question.id}"
        )
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))

    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def get_client_ip(request):
    """Get the visitor’s IP address using request headers."""
    if request:
        x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            ip = x_forwarded_for.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
        return ip
    return None


@receiver(user_logged_in)
def login_success(sender, request, user, **kwargs):
    """Log when user successfully login."""
    ip_addr = get_client_ip(request)
    logger.info(f"{user.username} logged in from {ip_addr}")


@receiver(user_logged_out)
def logout_success(sender, request, user, **kwargs):
    """Log when user successfully log out."""
    ip_addr = get_client_ip(request)
    logger.info(f"{user.username} logged out from {ip_addr}")


@receiver(user_login_failed)
def login_fail(sender, credentials, request, **kwargs):
    """Log when user failed to login."""
    ip_addr = get_client_ip(request)
    logger.warning(f"Failed login for {credentials['username']} from {ip_addr}")

polls/templates/polls/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  {% block title %}
  <title>KU Polls</title>
  {% endblock %}
</head>

<body>
  {% block header %}
  <div class="top-container">
    <a href="{% url 'polls:index' %}">
      <h1 class="header polls-header">
        KU Polls
      </h1>
    </a>
  
    {% if user.is_authenticated %}
    <form action="{% url 'logout' %}" method="post" class="auth-container">
      {% csrf_token %}
        Welcome&nbsp;Back,&nbsp;{{user.username}}
        <button type="submit" class="button auth-button">LOG OUT</button>
      </form>
    {% else %}
    <div class="auth-container">
      <a href="{% url 'login' %}?next={{request.path}}">
        <button type="submit", class="button auth-button">
          Login
        </button>
      </a>
    </div>
    {% endif %}
  </div>
  
  {% if messages %}
    {% for msg in messages %}
      <div class = "messages {{msg.tags}}">{{msg}}</div>
    {%endfor%}
  {% endif %}
  {% endblock %}


  {% block content %}
  {% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base_template.html' %}

{% block title %}
  <title>
    {{question.question_text}}
  </title>
{% endblock %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post" class="form">
  {% csrf_token %}
  <fieldset>
    <legend><h1 class="header detail-header">{{ question.question_text }}</h1></legend>

    {% for choice in question.choice_set.all %}
      {% if marked_choice == choice %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}", checked="checked">
      {% else %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      {% endif %}
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" class="button form-button">
</form>

{% if marked_choice %}
  <form action="{% url 'polls:unvote' question.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="button poll-delete-button" method="post">Delete Vote</button>
  </form>
{% endif %}

<a href="{% url 'polls:results' question.id %}">
  <button type="submit" class="button">Results</button>
</a>

<a href = {% url 'polls:index' %}>
  <button type="submit" class="button">Back to List of Polls</button>
</a>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base_template.html' %}

{% block title %}
  <title>
    Index - KU Polls
  </title>
{% endblock %}

{% block content %}
{% if latest_question_list %}
  {% for question in latest_question_list %}
    <div class="row">

      <div class="long-column">
        <a href="{% url 'polls:detail' question.id %}">
          {{question.question_text}}
        </a>
      </div>

      <div class="column">
        <a href="{% url 'polls:results' question.id %}">
          results
        </a>
      </div>
      
      {% if question.can_vote %}
        <div class="long-column open-poll">
          Status : Open
        </div>
      {% else %}
        <div class="long-column closed-poll">
          Status : Closed
        </div>
      {% endif %}

    </div>
  {% endfor %}
{% else %}
  <p class="error">No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base_template.html' %}

{% block title %}
  <title>
    Results - {{question.question_text}}
  </title>
{% endblock %}

{% block content %}
<h1 class="header">{{question.question_text}}</h1>
  
{% for choice in question.choice_set.all %}
<div class="row">
  <div class="column">
    {{choice.choice_text}}
  </div>
  <div class="column">
    {{choice.votes}}
  </div>
</div>
{% endfor %}

<a href = {% url 'polls:index' %}>
  <button type="submit" class="button result-button">
    Back to List of Polls
  </button>
</a>  

{% endblock %}